Merged PR 4777: Tutorials

diff --git a/.tekton/pipelines/docs-deploy.yaml b/.tekton/pipelines/docs-deploy.yaml
--- a/.tekton/pipelines/docs-deploy.yaml
+++ b/.tekton/pipelines/docs-deploy.yaml
@@ -46,6 +46,74 @@ spec:
       workspaces:
         - name: code
           workspace: code
+    - name: poetry-install-oneml-processors
+      retries: 3
+      taskSpec:
+        params:
+          - name: docker-image-app-builder
+            type: string
+            default: immunodata.azurecr.io/immunodata-app-builder:2022-08-29.23-56-49
+            description: The docker image for the app builder.
+          - name: component
+            type: string
+            description: component to install packages for
+        steps:
+          - name: poetry-install
+            image: "$(params.docker-image-app-builder)"
+            script: |
+              #!/usr/bin/env bash
+
+              # Fail on anything weird.
+              set -euo pipefail
+
+              source /root/.sourced_values
+
+              export DEVOPS_PYPI_UN="immunomics-artifacts"
+              export DEVOPS_PYPI_PW=$PYTHON_ARTIFACTS_PAT
+              export DEVOPS_PYPI_DOMAIN="pkgs.dev.azure.com/immunomics/_packaging/immunomics-artifacts/pypi/simple"
+              export DEVOPS_PYPI_URL="https://$DEVOPS_PYPI_UN:$DEVOPS_PYPI_PW@$DEVOPS_PYPI_DOMAIN"
+
+              export POETRY_HTTP_BASIC_IMMUNOMICS_ARTIFACTS_PASSWORD=$DEVOPS_PYPI_PW
+
+              export PIPENV_VENV_IN_PROJECT=t
+              export PYENV_SHELL=bash
+              export SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0
+
+              export IMMUNODATA_USER_EMAIL="tekton-pipeline@managed-identity"
+              export PROJECT_PATH="$(workspaces.code.path)"
+
+              export POETRY_DYNAMIC_VERSIONING_BYPASS=0.0.0
+              poetry config virtualenvs.in-project true
+
+              immunocli-next -vvv ci poetry-install --component $(params.component) --path "$(workspaces.code.path)"
+            resources:
+              limits:
+                memory: "10Gi"
+                cpu: "4"
+              requests:
+                memory: "10Gi"
+                cpu: "4"
+            env:
+              - name: PYTHON_ARTIFACTS_PAT
+                valueFrom:
+                  secretKeyRef:
+                    name: python-artifacts-pat
+                    key: pat
+              - name: "IMMUNOCLI_HABITAT"
+                value: "msft"
+        workspaces:
+          - name: code
+            description: The folder that stores the repo
+      runAfter:
+        - clone
+      params:
+        - name: docker-image-app-builder
+          value: "$(params.docker-image-app-builder)"
+        - name: component
+          value: oneml-processors
+      workspaces:
+        - name: code
+          workspace: code
     - name: mkdocs-build
       taskSpec:
         params:
@@ -99,6 +167,7 @@ spec:
           - name: code
             description: The folder that stores the repo
       runAfter:
+        - poetry-install-oneml-processors
       params:
         - name: docker-image-app-builder
           value: "$(params.docker-image-app-builder)"
